name: dont_forget_market
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  uuid: ^3.0.7
  shared_preferences: ^2.0.18
  flutter_launcher_icons: ^0.12.0
  flutter_native_splash: ^2.2.19

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path_android: "lib/assets/icon/android.png"
  image_path_ios: "lib/assets/icon/ios.png"
  remove_alpha_ios: true

flutter_native_splash:
  color: "#6A3DE8"
  image: "lib/assets/icon/splash.png"
  android: true
  ios: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
